server:
  port: 8088
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://database:5432/spartahubflow
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  data:
    redis:
      host: redis
      port: 6379
      password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

service:
  jwt:
    access-expiration: 3600000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"



springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api/v1/user/swagger
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**


management:
  zipkin:
    tracing:
      endpoint: "zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true