services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: spartahubflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d spartahubflow"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"

  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"

  eureka:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./eureka-server
    ports:
      - "8761:8761"

  gateway:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./gateway
    ports:
      - "8080:8080"

  product:
    environment:
      AI_SECRET_KEY: ${AI_SECRET_KEY}
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./product
    depends_on:
      database:
        condition: service_healthy

    ports:
      - "8085:8085"

  order:
    environment:
      AI_SECRET_KEY: ${AI_SECRET_KEY}
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./order
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8084:8084"

  company:
    environment:
      AI_SECRET_KEY: ${AI_SECRET_KEY}
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./company
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8081:8081"

  slack:
    environment:
      SLACK_TOKEN: ${SLACK_TOKEN}
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./slack
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8087:8087"

  hub:
    environment:
     GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./hub
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8083:8083"

  delivery:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./delivery
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8082:8082"

  redis:
    image: redis/redis-stack
    container_name: redis
    restart: always
    environment:
      REDIS_ARGS: "--requirepass 1234"
    ports:
      - "6379:6379"
      - "8001:8001"

  user:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./user
    ports:
      - "8088:8088"